version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: exercise-5-postgres
    restart: always
    environment:
      POSTGRES_USER: akshat
      POSTGRES_PASSWORD: akshat20112002
      POSTGRES_DB: exercise5
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akshat"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    image: "exercise-5"
    container_name: exercise-5-test
    volumes:
      - .:/app
    command: python3 -m pytest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: akshat
      DB_PASSWORD: akshat20112002
      DB_NAME: exercise5

  run:
    image: "exercise-5"
    container_name: exercise-5-run
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      RUNNING_IN_DOCKER: "true"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: akshat
      DB_PASSWORD: akshat20112002
      DB_NAME: exercise5
    command: python3 main.py
    depends_on:
      postgres:
        condition: service_healthy
